### ISSUE TITLE
Repository is not present.

### ISSUE THREAD

**Issue by paliwalprateek1** [softwareengpro/Offline-Typeracer#1]
When I found out about your project, I I thrilled to find out that now there's an offline type-racer game. Earlier whenever I used to practice type-racer I was often disturbed by other WiFi users watching anti social videos on YouTube. So this project was looking very helpful for me. But when I found out that there's no repo created I was deeply disheartened and anguished to my very core. I am very disappointed with this. Please clear my issue.

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by paliwalprateek1** [comment]
P. S. : It is "I was thrilled......."
Thanks

**Comment by vermanil** [comment]
Okk, Done
